### ISSUE TITLE
“NoSuchMethodErrors” due to multiple versions of org.mongodb:mongo-java-driver:jar

### ISSUE THREAD

**Issue by Bing-ok** [mongobee/mongobee#119]
## Issue description
Hi, there are multiple versions of **_org.mongodb:mongo-java-driver_** in **_mongobee-master_**. As shown in the following dependency tree, according to Maven's “nearest wins” strategy, only **_org.mongodb:mongo-java-driver:3.3.0_** can be loaded, **_org.mongodb:mongo-java-driver:2.12.3_** will be shadowed.

However, several methods defined in shadowed version **_org.mongodb:mongo-java-driver:2.12.3_** is referenced by client project **_org.springframework.data:spring-data-mongodb:1.6.1.RELEASE_**, but missing in the actually loaded version **_org.mongodb:mongo-java-driver:3.3.0_**.

For instance, the following missing method(defined in **_org.mongodb:mongo-java-driver:2.12.3_**) are actually referenced by **_mongobee-master_**, which will introduce a runtime error(i.e., "NoSuchMethodError") into **_mongobee-master_**.

**_1. com.mongodb.DB: boolean isAuthenticated()_** is invoked by **_mongobee-master_** via the following path:
<pre><code>
paths------
&lt;com.github.mongobee.Mongobee: void execute()&gt; mongobee-master\target\classes
&lt;com.github.mongobee.Mongobee: void executeMigration()&gt; mongobee-master\target\classes
&lt;com.github.mongobee.Mongobee: java.lang.Object executeChangeSetMethod(java.lang.reflect.Method,java.lang.Object,com.mongodb.DB,com.mongodb.client.MongoDatabase)&gt; mongobee-master\target\classes
&lt;org.springframework.data.mongodb.core.MongoTemplate: void init (com.mongodb.Mongo,java.lang.String)&gt; Repositories\org\springframework\data\spring-data-mongodb\1.6.1.RELEASE\spring-data-mongodb-1.6.1.RELEASE.jar
&lt;org.springframework.data.mongodb.core.MongoTemplate: void init (org.springframework.data.mongodb.MongoDbFactory,org.springframework.data.mongodb.core.convert.MongoConverter)&gt; Repositories\org\springframework\data\spring-data-mongodb\1.6.1.RELEASE\spring-data-mongodb-1.6.1.RELEASE.jar
&lt;org.springframework.data.mongodb.core.index.MongoPersistentEntityIndexCreator: void init (org.springframework.data.mongodb.core.mapping.MongoMappingContext,org.springframework.data.mongodb.MongoDbFactory)&gt; Repositories\org\springframework\data\spring-data-mongodb\1.6.1.RELEASE\spring-data-mongodb-1.6.1.RELEASE.jar
&lt;org.springframework.data.mongodb.core.index.MongoPersistentEntityIndexCreator: void init (org.springframework.data.mongodb.core.mapping.MongoMappingContext,org.springframework.data.mongodb.MongoDbFactory,org.springframework.data.mongodb.core.index.IndexResolver)&gt; Repositories\org\springframework\data\spring-data-mongodb\1.6.1.RELEASE\spring-data-mongodb-1.6.1.RELEASE.jar
&lt;org.springframework.data.mongodb.core.index.MongoPersistentEntityIndexCreator: void checkForIndexes(org.springframework.data.mongodb.core.mapping.MongoPersistentEntity)&gt; Repositories\org\springframework\data\spring-data-mongodb\1.6.1.RELEASE\spring-data-mongodb-1.6.1.RELEASE.jar
&lt;org.springframework.data.mongodb.core.index.MongoPersistentEntityIndexCreator: void checkForAndCreateIndexes(org.springframework.data.mongodb.core.mapping.MongoPersistentEntity)&gt; Repositories\org\springframework\data\spring-data-mongodb\1.6.1.RELEASE\spring-data-mongodb-1.6.1.RELEASE.jar
&lt;org.springframework.data.mongodb.core.index.MongoPersistentEntityIndexCreator: void createIndex(org.springframework.data.mongodb.core.index.MongoPersistentEntityIndexResolver$IndexDefinitionHolder)&gt; Repositories\org\springframework\data\spring-data-mongodb\1.6.1.RELEASE\spring-data-mongodb-1.6.1.RELEASE.jar
&lt;org.springframework.data.mongodb.core.SimpleMongoDbFactory: com.mongodb.DB getDb()&gt; Repositories\org\springframework\data\spring-data-mongodb\1.6.1.RELEASE\spring-data-mongodb-1.6.1.RELEASE.jar
&lt;org.springframework.data.mongodb.core.SimpleMongoDbFactory: com.mongodb.DB getDb(java.lang.String)&gt; Repositories\org\springframework\data\spring-data-mongodb\1.6.1.RELEASE\spring-data-mongodb-1.6.1.RELEASE.jar
&lt;org.springframework.data.mongodb.core.MongoDbUtils: com.mongodb.DB getDB(com.mongodb.Mongo,java.lang.String,org.springframework.data.authentication.UserCredentials,java.lang.String)&gt; Repositories\org\springframework\data\spring-data-mongodb\1.6.1.RELEASE\spring-data-mongodb-1.6.1.RELEASE.jar
&lt;org.springframework.data.mongodb.core.MongoDbUtils: com.mongodb.DB doGetDB(com.mongodb.Mongo,java.lang.String,org.springframework.data.authentication.UserCredentials,boolean,java.lang.String)&gt; Repositories\org\springframework\data\spring-data-mongodb\1.6.1.RELEASE\spring-data-mongodb-1.6.1.RELEASE.jar
&lt;com.mongodb.DB: boolean isAuthenticated()&gt;
</code></pre>

**_2. com.mongodb.DB: boolean authenticate(java.lang.String,char[])_** is invoked by **_mongobee-master_** via the following path:
<pre><code>
paths------
&lt;com.github.mongobee.Mongobee: void execute()&gt; mongobee-master\target\classes
&lt;com.github.mongobee.Mongobee: void executeMigration()&gt; mongobee-master\target\classes
&lt;com.github.mongobee.Mongobee: java.lang.Object executeChangeSetMethod(java.lang.reflect.Method,java.lang.Object,com.mongodb.DB,com.mongodb.client.MongoDatabase)&gt; mongobee-master\target\classes
&lt;org.springframework.data.mongodb.core.MongoTemplate: void init (com.mongodb.Mongo,java.lang.String)&gt; Repositories\org\springframework\data\spring-data-mongodb\1.6.1.RELEASE\spring-data-mongodb-1.6.1.RELEASE.jar
&lt;org.springframework.data.mongodb.core.MongoTemplate: void init (org.springframework.data.mongodb.MongoDbFactory,org.springframework.data.mongodb.core.convert.MongoConverter)&gt; Repositories\org\springframework\data\spring-data-mongodb\1.6.1.RELEASE\spring-data-mongodb-1.6.1.RELEASE.jar
&lt;org.springframework.data.mongodb.core.index.MongoPersistentEntityIndexCreator: void init (org.springframework.data.mongodb.core.mapping.MongoMappingContext,org.springframework.data.mongodb.MongoDbFactory)&gt; Repositories\org\springframework\data\spring-data-mongodb\1.6.1.RELEASE\spring-data-mongodb-1.6.1.RELEASE.jar
&lt;org.springframework.data.mongodb.core.index.MongoPersistentEntityIndexCreator: void init (org.springframework.data.mongodb.core.mapping.MongoMappingContext,org.springframework.data.mongodb.MongoDbFactory,org.springframework.data.mongodb.core.index.IndexResolver)&gt; Repositories\org\springframework\data\spring-data-mongodb\1.6.1.RELEASE\spring-data-mongodb-1.6.1.RELEASE.jar
&lt;org.springframework.data.mongodb.core.index.MongoPersistentEntityIndexCreator: void checkForIndexes(org.springframework.data.mongodb.core.mapping.MongoPersistentEntity)&gt; Repositories\org\springframework\data\spring-data-mongodb\1.6.1.RELEASE\spring-data-mongodb-1.6.1.RELEASE.jar
&lt;org.springframework.data.mongodb.core.index.MongoPersistentEntityIndexCreator: void checkForAndCreateIndexes(org.springframework.data.mongodb.core.mapping.MongoPersistentEntity)&gt; Repositories\org\springframework\data\spring-data-mongodb\1.6.1.RELEASE\spring-data-mongodb-1.6.1.RELEASE.jar
&lt;org.springframework.data.mongodb.core.index.MongoPersistentEntityIndexCreator: void createIndex(org.springframework.data.mongodb.core.index.MongoPersistentEntityIndexResolver$IndexDefinitionHolder)&gt; Repositories\org\springframework\data\spring-data-mongodb\1.6.1.RELEASE\spring-data-mongodb-1.6.1.RELEASE.jar
&lt;org.springframework.data.mongodb.core.SimpleMongoDbFactory: com.mongodb.DB getDb()&gt; Repositories\org\springframework\data\spring-data-mongodb\1.6.1.RELEASE\spring-data-mongodb-1.6.1.RELEASE.jar
&lt;org.springframework.data.mongodb.core.SimpleMongoDbFactory: com.mongodb.DB getDb(java.lang.String)&gt; Repositories\org\springframework\data\spring-data-mongodb\1.6.1.RELEASE\spring-data-mongodb-1.6.1.RELEASE.jar
&lt;org.springframework.data.mongodb.core.MongoDbUtils: com.mongodb.DB getDB(com.mongodb.Mongo,java.lang.String,org.springframework.data.authentication.UserCredentials,java.lang.String)&gt; Repositories\org\springframework\data\spring-data-mongodb\1.6.1.RELEASE\spring-data-mongodb-1.6.1.RELEASE.jar
&lt;org.springframework.data.mongodb.core.MongoDbUtils: com.mongodb.DB doGetDB(com.mongodb.Mongo,java.lang.String,org.springframework.data.authentication.UserCredentials,boolean,java.lang.String)&gt; Repositories\org\springframework\data\spring-data-mongodb\1.6.1.RELEASE\spring-data-mongodb-1.6.1.RELEASE.jar
&lt;com.mongodb.DB: boolean authenticate(java.lang.String,char[])&gt;
</code></pre>

## Suggested fixing solutions
Upgrade dependency **_org.springframework.data:spring-data-mongodb_** from **_1.6.1.RELEASE_** to **_1.10.0.RELEASE_**. Because the newer version **_org.springframework.data:spring-data-mongodb:1.10.0.RELEASE_** does not invoke the above missing method, such upgrading can solve the problem.

Thank you very much for your attention.
Best regards,

## Dependency tree----
<pre><code>
[INFO] com.github.mongobee:mongobee:jar:0.14-SNAPSHOT
[INFO] +- <b>org.mongodb:mongo-java-driver:jar:3.3.0:compile</b>
[INFO] \- org.springframework.data:spring-data-mongodb:jar:1.6.1.RELEASE:compile
[INFO]    \- <b>(org.mongodb:mongo-java-driver:jar:2.12.3:compile - omitted for conflict with 3.3.0)</b>
</code></pre>

**Comment by Bing-ok** [comment]
Could you help me review this issue? 👍 Thanks! @mongobee

**Comment by mjustin-rr19** [comment]
By all appearances, this project was abandoned in 2018.  [Mongock](https://www.mongock.io) is an actively maintained successor library which [supports migration from Mongobee](https://www.mongock.io/legacy-migration#mongobee-scenario).  Migrating to Mongock will be the most straightforward option in your situation.
