### ISSUE TITLE
unresolved dependency on jfrog.jade

### ISSUE THREAD

**Issue by abelski** [mongobee/mongobee#22]
Clear .m2 folder and try mvn package

[WARNING] The POM for org.jfrog.jade.plugins.common:jade-plugin-common:jar:1.3.8 is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.485s
[INFO] Finished at: Thu Nov 20 18:24:57 MSK 2014
[INFO] Final Memory: 12M/489M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project mongobee: Could not resolve dependencies for project com.github.mongobee:mongobee:jar:0.9-SNAPSHOT: Failure to find org.jfrog.jade.plugins.common:jade-plugin-common:jar:1.3.8 in http://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by MohanCylsys** [comment]
please give reference how you fixed it this issue.
