### ISSUE TITLE
Release 0.10?

### ISSUE THREAD

**Issue by RealNitro** [mongobee/mongobee#28]
We're currently using Mongobee 0.9. That version still eats most of the exceptions, making debugging of problems on remote systems hard for us. We would like to move to a version that passes the cause of the exceptions, like the current Mongobee git master does. When do you plan on releasing the next version of Mongobee, including the exception changes?

**Comment by mongobee** [comment]
Hi, Actually this version is ready to release so I will do it today. Thanks for the reminder :)

**Comment by RealNitro** [comment]
That's great news, thanks!

**Comment by mongobee** [comment]
released
