### ISSUE TITLE
Custom MongoTemplate support

### ISSUE THREAD

**Issue by cowens85** [mongobee/mongobee#29]
We use a custom MappingMongoConverter in our application. To do this with mongobee, we would need it to support custom MongoTemplates. The template that is used is currently newed up in a private method, restricting our ability to override it.

**Comment by cowens85** [comment]
Any timeline on this, or want some help with it? I wouldn't mind making the enhancement.

**Comment by mongobee** [comment]
hi. I had no time recently :( If you are eager, please feel free to do that. Just make the fork and then create a pull request. I will merge it after code review :) Thanks :)

**Comment by cowens85** [comment]
That looks good for completing this issue/enhancement. I'd love to be able to override the executeChangeSetMethod as well, but that may be a different enhancement. Thanks!

**Comment by mongobee** [comment]
released in ver. 0.11
