### ISSUE TITLE
Fix wiki

### ISSUE THREAD

**Issue by abelski** [mongobee/mongobee#31]
org.springframework.beans.NotWritablePropertyException: Invalid property 'changelogsBasePackage' of bean class [com.github.mongobee.Mongobee]: Bean property 'changelogsBasePackage' is not writable or has an invalid setter method. Does the parameter type of the setter match the return type of the getter?

<bean id="mongobee" class="com.github.mongobee.Mongobee">
        <constructor-arg value="mongodb://localhost:27017/citanda"/>
        <property name="dbName" value="citanda"/>
        <property name="enabled" value="true"/>
        <property name="changeLogsScanPackage"
                  value="com.egx.citanda.db.init"/>
    </bean>

i guess example in wiki not correct

**Comment by mongobee** [comment]
wiki fixed. thanks!
