### ISSUE TITLE
Reduce mongobee dependencies

### ISSUE THREAD

**Issue by madmuffin1** [mongobee/mongobee#34]
I do like the idea of mongobee using Java classes instead of hard-to-maintain xml files and would love to see a plugin-structure in the near future.

Currently mongobee requires jongo, mongodb-driver and spring, in the near future (pr #33) morphia will be added.
All of these bring their own dependencies along, which sums up to ~ 8MB.

Also we experienced a version incompatibility with a jackson version in our project and the jackson version required by jongo.

mongobee should probably just be the core, that contains the logic to run migrations and that keeps track of the migrations that were applied so far. further making it possible to install mongobee-jongo if one decides to go the jongo way, mongobee-spring or mongobee-morphia. 
This will reduce the size of the library and allow for easier enhancements.

If @lstolowski generally agrees on such an idea, I would consider adapting mongobee accordingly.

**Comment by hoegertn** [comment]
+1

**Comment by DevWantJustHaveFun** [comment]
+1

**Comment by ejrav** [comment]
+1

**Comment by agiannone** [comment]
+1

**Comment by derekbassett** [comment]
+1

**Comment by blafoo** [comment]
@madmuffin1 Have a look at [MongoBumblebee](https://github.com/hdisysteme/MongoBumblebee). It's available at Maven Central and works with Spring Boot 3 and Java 17.
