### ISSUE TITLE
Multiple processes race condition?

### ISSUE THREAD

**Issue by colsson11** [mongobee/mongobee#35]
Hi there,

it seems to me that there is no protection from race conditions between multiple processes currently. Is this correct or am I missing something? 

I'd like to use the application on-startup integration (via Spring), in an environment with multiple servers, but without additional configuration to enable Mongobee on just one server.

One idea here could be to implement a global process semaphore via e.g. the method described here http://stackoverflow.com/a/16362833. So on execution startup the semaphore would be set, and then cleared on exit, ensuring only one process at a time is run.

Would there be interest in a pull request like this? Any other suggestions?

Cheers,

Christian

**Comment by mongobee** [comment]
Hi
No there is no such mechanism at the moment. 
I see two solutions here:
1. Use 'enabled' option set to 'false' (see wiki pt. 2.1 or 2.2). You could set this flag based on some application property or server name etc...

or

2. You could use @Profile annnotation (on whole ChangeLog class) and set different Spring's profiles on different servers.

In similar cases at my work I used to implement first solution more often but it depends on your architecture and configuration.

**Comment by colsson11** [comment]
Hi there,

thanks for your response.

Yeah those solutions should work, it's just that I would like to avoid having different configuration for servers, to keep things simple.

It seems like adding a global lock for the process based on the approach above should be reasonably straightforward. This could of course be opt out (or opt in?) also. If I implement this, would you be interested in merging a pull request like this?

Cheers,

Christian

**Comment by mongobee** [comment]
Sure, if you want. Everybody is welcome to develop this soft :)

**Comment by RutledgePaulV** [comment]
I noticed that a lock implementation was committed by @colsson11 . Does that mean this issue can be closed?

**Comment by colsson11** [comment]
Should be fine - closing.

**Comment by ameyg7** [comment]
1)Consider case having node1 & node2...both are getting started simultaneously
2)node 1 acquired lock before node 2..consider changelog has almost 50 DB scripts which has to be executed on DB.

So which of the case will work as per the solution implemented?
1)Node2 will be on halt till the time lock is released from node 1 & node 2 will start further execution once all 50 scrips have been executed from node 1 ie node 2 will wait till node 1 finished all scripts ?
2)Node 2 will be up before all those 50 scripts have been executed from node 1? ie node2 will not wait for node 1 completion & will be up before node1 finishes all DB scripts?

What is the implementation behavior @colsson11 @mongobee @RutledgePaulV
