### ISSUE TITLE
Add a way to define rollback changesets

### ISSUE THREAD

**Issue by jamesmmchugh** [mongobee/mongobee#40]
Great tool but it would be useful to have a way to define rollbacks to changesets programmatically.

**Comment by lstolowski** [comment]
mongodb is a no-transactional db. This feature would be to complicated for such simple tool.

**Comment by zy4** [comment]
Well, this changed with [MongoDB 4.0](https://www.mongodb.com/transactions).
Are you interested in a PR for supporting this feature?
