### ISSUE TITLE
Is this library still supported?

### ISSUE THREAD

**Issue by gurrie** [mongobee/mongobee#41]
Hi 

I would like to use this library in my project but would like to know if it is still supported?

Regards
Brian

**Comment by mongobee** [comment]
It is, but I need to brace myself to merge all merge requests.. :)
Soon I will have some free time to do that.

**Comment by gurrie** [comment]
Ok great thanks for the quick response! And good luck :-)

**Comment by gurrie** [comment]
I was also wondering whether you have ever used the library in a clustered env? From looking at the code it seems that there is a race condition whereby multiple servers could attempt the same changeset? Or am I missing something

**Comment by mongobee** [comment]
No, there is no such feature to prevent launching the same ChangeSet in the same time on different nodes. If nodes are using the same DB and starting mongobee process in the same time then changeset can be executed twice.

I used mongobee in multi-node architecture but we always deployed nodes one-by-one (and load balancer ensured that system is always online for end user).

Probably it is good to implement similar solution as [Liquibase](http://liquibase.org) has: add a collection dbchagelog_lock with values '1' or '0' - it will work like a semafore for all nodes.

**It needs to be thought over ** and implement.  I will add a separate issue for that
