### ISSUE TITLE
Launching ChangeLogs in multi-nodes architecture

### ISSUE THREAD

**Issue by mongobee** [mongobee/mongobee#44]
**Problem**:
I was also wondering whether you have ever used the library in a clustered env? From looking at the code it seems that there is a race condition whereby multiple servers could attempt the same changeset? Or am I missing something

**Answer**:
No, there is no such feature to prevent launching the same ChangeSet in the same time on different nodes. If nodes are using the same DB and starting mongobee process in the same time then changeset can be executed twice.
I used mongobee in multi-node architecture but we always deployed nodes one-by-one (and load balancer ensured that system is always online for end user).

**Possible Solution**:
Probably it is good to implement similar solution as Liquibase has: add a collection dbchagelog_lock with values '1' or '0' - it will work like a semafore for all nodes.

*It needs to be thought over* and implement. I will add a separate issue for that

**Comment by kevinstembridge** [comment]
I might be missing something but does this issue address the same issue raised in #35 ?

**Comment by lstolowski** [comment]
#35
