### ISSUE TITLE
How to pass collection names into ChangeLog

### ISSUE THREAD

**Issue by poggio84** [mongobee/mongobee#45]
Hi guys, any suggestion on how to pass the name of the collection(s) into the `@ChangeLog` script from another class (from main for example)?

Thanks
Diego

**Comment by lstolowski** [comment]
Could you describe what you want to do? Do you mean some kind of injection?

My first thought was to put there a reference to static String with the name of a collection, but I'm not sure you're asking for such solution :)

**Comment by poggio84** [comment]
Yes I had the same idea :)
I have a class annotated with `@ChangeLog` containing all my `@ChangeSet` then when I'm doing 
`MongoCollection<Document> mycollection = db.getCollection("mycollection");`
I would like the "mycollection" value as class variable and be able to set it from outside. Constructor is not an option (I guess) like setters.. plus I would like to avoid spring dependency and a property files as well.
So the static reference is the only solution that I can think.
Suggestions? 

Thanks for your help

**Comment by lstolowski** [comment]
> _So the static reference is the only solution that I can think._
Yes, I think so.

ChangeLog class is a log of your changes. So maybe it is good to hardcode names of collections/fields/indexes in ChangeSets. It shows a state of your DB and your development in point of time and all your changes over time.
Anyway, as ChangeSets are not "checksummed" (technically, Java method cannot be checksummed) so your dynamic improvement won't brake anything :)

**Comment by lstolowski** [comment]
Hi @poggio84 
Do you have any other questions or concerns about this issue?

**Comment by poggio84** [comment]
No I'm fine
Thanks for your help
