### ISSUE TITLE
Codecs for nested entities

### ISSUE THREAD

**Issue by salimchami** [mongobee/mongobee#50]
Hello!

What about nested entities ? 
How can we do to serialize automatically entities with nested ones ?

I have multiple entities and nested entities, and when I execute db migration, I have this exception : 

```
Caused by: com.github.mongobee.exception.MongobeeException: Can't find a codec for class com.......Address.
	at com.github.mongobee.Mongobee.execute(Mongobee.java:173)
	at com.github.mongobee.Mongobee.afterPropertiesSet(Mongobee.java:117)
```

``` 
Caused by: org.bson.codecs.configuration.CodecConfigurationException: Can't find a codec for class com....Address.
	at org.bson.codecs.configuration.CodecCache.getOrThrow(CodecCache.java:46)
	at org.bson.codecs.configuration.ProvidersCodecRegistry.get(ProvidersCodecRegistry.java:63)
```

**Comment by mongobee** [comment]
It looks like problem with official mongodb driver. Mongobee relies on that driver.
Maybe try this: http://stackoverflow.com/questions/31237849/cant-find-a-codec-for-class-com-mongodb-basicdbobject-error-in-java-using-mondo#35856263
You can specify your MongoClient.

**Comment by salimchami** [comment]
Thanks for your response.

I always have the same problem. Here is my mongobee method for db migration : 

```java
@Configuration
@Profile("!" + Constants.SPRING_PROFILE_CLOUD)
@EnableMongoRepositories("com.wideapps.schoolme.repository")
@Import(value = MongoAutoConfiguration.class)
@EnableMongoAuditing(auditorAwareRef = "springSecurityAuditorAware")
public class DatabaseConfiguration {

    @Bean
    public Mongobee mongobeeCommonEnv(MongoClient mongo, MongoProperties mongoProperties) {
        MongoClientOptions settings = MongoClientOptions.builder().readPreference(ReadPreference.nearest())
            .codecRegistry(com.mongodb.MongoClient.getDefaultCodecRegistry()).build();
        MongoClient mongoClient = new MongoClient(mongoProperties.getHost(), settings);
        Mongobee mongobee = new Mongobee(mongoClient);
        mongobee.setDbName(mongoProperties.getDatabase());
        log.debug("--------------> Configuring Mongobee for Common Env...");
        mongobee.setChangeLogsScanPackage(COMMON_DB_MIGRATION_PACKAGE);
        mongobee.setEnabled(true);
        return mongobee;
    }

}
```

It's the jhipster databaseconfiguration class.
In my change, i have only a simple dbCollection.insert... 
But the inserted entity contains a nested entity (Address).

**Comment by Vatrax** [comment]
Hi. 
I have the same problem. Spring data does not have any problems (saving object schema after migration) with conversion, but when using mongobee I am facing the same exception.

**Comment by chamini2** [comment]
Bump

**Comment by salimchami** [comment]
The solution is to add a codec registry : 
http://mongodb.github.io/mongo-java-driver/3.7/driver/getting-started/quick-start-pojo/
