### ISSUE TITLE
Contact details

### ISSUE THREAD

**Issue by SirWayne** [mongobee/mongobee#78]
Does anyone know the contact details of mongobee?

We would like to contribute a lot to this project or is the project dead?

**Comment by lstolowski** [comment]
Would be great if you find some time to contribute
I don't have time at the moment. What do you want to do, which issue you want to start with? :)

**Comment by MelleD** [comment]
Can you write me an e-mail dennis.melzer@de.bosch.com? I would like to discuss a few things about the project and further cooperation

**Comment by javisst** [comment]
It's the most feature rich migration tool for mongo. Unfortunately with too many open PRs and old dependencies. Let people help you 😄
